### ISSUE TITLE
Strange discount value that doesn't get applied

### ISSUE THREAD

**Issue by ionambrinoc** [vtex-apps/order-quote#20]
**Describe the bug**
Please see https://www.dacris.net/orderquote/view/58b811d5-fcd7-11ea-8367-0e5fdc67f5d3
The difference between the subtotal and total is 2.5 lei, whereas the discounts shown are -860 000,00 lei - which is not in the same ballpark.
Screenshot from customer: https://share.getcloudapp.com/wbu7RGkQ

**To Reproduce**
Add the above products into basket and use the order quote app v 1.1.5.
**Screenshots**
https://share.getcloudapp.com/wbu7RGkQ

**Comment by ionambrinoc** [comment]
When creating a order quote from a cart, the column for the reference code is empty.
Also, at the bottom of the quote there is a summary block that shows the subtotal, delivery costs, discounts and the total but the taxes are missing. Seeing as we use taxes for VAT (that is 19%) we need to show this value, as it is really important.

https://share.getcloudapp.com/xQuYLrNl

**Comment by wender** [comment]
> **Describe the bug**
> Please see https://www.dacris.net/orderquote/view/58b811d5-fcd7-11ea-8367-0e5fdc67f5d3
> The difference between the subtotal and total is 2.5 lei, whereas the discounts shown are -860 000,00 lei - which is not in the same ballpark.
> Screenshot from customer: https://share.getcloudapp.com/wbu7RGkQ
> 
> **To Reproduce**
> Add the above products into basket and use the order quote app v 1.1.5.
> **Screenshots**
> https://share.getcloudapp.com/wbu7RGkQ

This specific issue was fixed, the inserted data was wrong so old quotations will not be fixed automatically
